teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.4
  scale_linear_turbo: 1.0
  axis_angular: 0
  scale_angular: 3.0
  scale_angular_turbo: 3.0
  enable_button: 0
  enable_turbo_button: 2
joy_node:
  deadzone: 0.12
  autorepeat_rate: 20
