<?xml version="1.0"?>
<!--

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.

-->

<robot xmlns:xacro = "http://ros.org/wiki/xacro">

	<xacro:macro name="wheel" params="sideY sideX positionY positionX reflect parent">
	    <link name="${sideY}_${sideX}_wheel_link">
	    	<visual>
	        	<origin xyz = "0 0 0" rpy = "0 ${-PI / 2} 0"/>
	        	<geometry>
	          		<mesh filename="package://canyonero_description/meshes/canyonero_wheel.stl"/>
	        	</geometry>
	        	<material name = "Black"/>
	      	</visual>
		    <inertial>
		    	<origin xyz="0.0 0.0 0.102638" rpy="0 0 0"/>
		        <mass value="1.419"/>
		        <inertia ixx="0.01101" ixy="0.0000238" ixz="0.00000223198"
				        		 iyy="0.01104" iyz="${-0.00000012456 * reflect}"
				             izz="0.003326"/>

		    </inertial>
	      	<collision>
	        	<origin xyz="0 0 0" rpy="0 ${-PI / 2} 0"/>
	        	<geometry>
	          		<mesh filename = "package://canyonero_description/meshes/canyonero_wheel_collision.stl"/>
	        	</geometry>
	      	</collision>
	      	<gazebo reference="${sideY}_${sideX}_wheel_link">
      			<material>Gazebo/Black</material>
    		</gazebo>
	    </link>

	    <joint name="${sideY}_${sideX}_wheel_joint" type="continuous">
	    	<parent link="${parent}_link"/>
	      	<child link="${sideY}_${sideX}_wheel_link"/>
	      	<origin xyz="${wheel_pos_X * positionX} ${wheel_pos_Y * positionY} ${-wheel_pos_Z}" rpy="${(PI / 2) * reflect} 0 0"/>
	      	<axis xyz="0 0 1"/>
	    </joint>

			<transmission name="simple_trans">
			  <type>transmission_interface/SimpleTransmission</type>
			  <joint name="${sideY}_${sideX}_wheel_joint">
					<hardwareInterface>EffortJointInterface</hardwareInterface>
			  </joint>
			  <actuator name="DC_motor">
					<mechanicalReduction>1</mechanicalReduction>
					<hardwareInterface>EffortJointInterface</hardwareInterface>
			  </actuator>
			</transmission>
  	</xacro:macro>
</robot>
