<?xml version="1.0"?>
<!--

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.

-->

<robot xmlns:xacro = "http://ros.org/wiki/xacro">

	<xacro:macro name="wheel" params="sideY sideX positionY positionX reflect parent torque velocity radius">
	    <link name="wheel_${sideX}_${sideY}_link">
	    	<visual>
	        	<origin xyz = "0 0 0" rpy = "0 ${-PI / 2} 0"/>
	        	<geometry>
	          		<mesh filename="package://canyonero_description/meshes/canyonero_wheel.stl"/>
	        	</geometry>
	        	<material name="Black"/>
	      	</visual>
		    <inertial>
		    	<origin xyz="0.0 0.0 0.102638" rpy="0 0 0"/>
		        <mass value="1.419"/>
		        <inertia ixx="0.00305" ixy="0.0" ixz="0.0"
				        		 iyy="0.00305" iyz="0.0"
				             izz="0.00512"/>

		    </inertial>
	      	<collision>
	        	<origin xyz="0 0 0" rpy="0 ${-PI / 2} 0"/>
	        	<geometry>
	          		<mesh filename="package://canyonero_description/meshes/canyonero_wheel_collision.stl"/>
	        	</geometry>
	      	</collision>
	    </link>

	    <joint name="wheel_${sideX}_${sideY}_joint" type="continuous">
	    	<parent link="${parent}_link"/>
	      	<child link="wheel_${sideX}_${sideY}_link"/>
	      	<origin xyz="${wheel_pos_X * positionX} ${wheel_pos_Y * positionY} ${-wheel_pos_Z}" rpy="${(PI / 2) * reflect} 0 0"/>
	      	<axis xyz="0 0 1"/>
					<limit effort="${torque}" velocity="${velocity / radius}"/>
	    </joint>

			<transmission name="simple_trans">
			  <type>transmission_interface/SimpleTransmission</type>
			  <joint name="wheel_${sideX}_${sideY}_joint">
					<hardwareInterface>VelocityJointInterface</hardwareInterface>
			  </joint>
			  <actuator name="DC_motor">
					<mechanicalReduction>1</mechanicalReduction>
			  </actuator>
			</transmission>

			<gazebo reference="wheel_${sideX}_${sideY}_link">
				<mu1 value="0.75"/>
				<mu2 value="0.75"/>
				<!--kp value="10000000.0" /-->
				<!--kd value="1.0" /-->
				<fdir1 value="0 0 0"/>
				<material value="Gazebo/Black"/>
			</gazebo>

  	</xacro:macro>
</robot>
